# Generated by Django 3.1.3 on 2020-11-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='html_content',
        ),
        migrations.RemoveField(
            model_name='program',
            name='description',
        ),
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
        migrations.RemoveField(
            model_name='section',
            name='order_index',
        ),
        migrations.RemoveField(
            model_name='section',
            name='overview_image',
        ),
    ]
