# Generated by Django 3.1.3 on 2020-11-15 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20201115_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='programs.section'),
        ),
    ]
