# Generated by Django 3.1.3 on 2020-11-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20201115_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='programs.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='programs.program'),
        ),
    ]
