# Generated by Django 3.1.3 on 2020-11-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20201116_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='programs.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='programs.program'),
        ),
    ]
