# Generated by Django 3.1.3 on 2020-11-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20201116_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='order_index',
            field=models.IntegerField(null=True),
        ),
    ]
