# Generated by Django 3.1.3 on 2020-11-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_auto_20201117_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='overview_image',
            field=models.URLField(blank=True),
        ),
    ]
