# Generated by Django 3.1.3 on 2020-11-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_section_overview_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('order_index',)},
        ),
    ]
