# Generated by Django 3.1.3 on 2020-11-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_auto_20201119_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='program',
        ),
        migrations.AddField(
            model_name='activity',
            name='sections',
            field=models.ManyToManyField(to='programs.Section'),
        ),
        migrations.AddField(
            model_name='section',
            name='programs',
            field=models.ManyToManyField(to='programs.Program'),
        ),
    ]
