# Generated by Django 3.1.3 on 2020-11-19 23:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_auto_20201119_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='choices',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
