# Generated by Django 3.1.3 on 2020-11-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_activity_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='choices',
            field=models.JSONField(null=True),
        ),
    ]
