# Generated by Django 3.1.3 on 2020-11-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_auto_20201119_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='choices',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
